spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pw
    url: jdbc:mysql://localhost:3306/lunit?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10000
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
jwt:
  secret: bHVuaXQtc3ByaW5nLWJvb3QtcHJvamVjdC1ieS0yeWVzZXVsLWxvbmdlci1sb25nZXItbG9uZ2VyLWxvbmdlci1sdW5pdC1wbGVhc2U=